services:
    mongo:
        image: mongo
        restart: always
        ports:
            - ${MONGO_SERVICE_PORT}:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - ./database/mongodb/data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - ${MONGO_EXPRESS_SERVICE_PORT}:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            #ME_CONFIG_MONGODB_ENABLE_ADMIN: true
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME} # mongo-express login username and password.
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD} # Use postgres/example user/password credentials
    postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      volumes:
        - ./postgres/db/:/var/lib/postgresql/data/
      #adminer:
      #image: dpage/pgadmin4
      #image: adminer
      #restart: always
      #ports:
      # - 5000:8080
